---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: Check for newrelic_appname
  fail:
    msg: "newrelic_appname has not been defined"
  when: newrelic_appname|default(False) == False

- include: debian.yml
  when: ( ansible_distribution == 'Debian' ) or ( ansible_distribution == 'Ubuntu' )

- include: redhat.yml
  when: ansible_distribution == 'RedHat'

- include: default.yml
  when: ansible_distribution|default(False) == False

- include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/default.yml"

- name: Configure New Relic PHP Agent
  template:
    src: newrelic.ini.j2
    dest: "{{ php_d_path }}/newrelic.ini"
    group: root
    owner: root
    mode: 0640
  notify:
    - Run New Relic Installer
  when: ansible_distribution|default(False) != False
